import '../../globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { getDictionary } from '@/utils/getDictionary';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  
}

export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ lang: string }>;
}) {
    const resolvedParams = await params;
  const lang = Array.isArray(resolvedParams.lang)
    ? resolvedParams.lang[0]
    : resolvedParams.lang;

  const safeLang = lang === "es" || lang === "en" ? lang : "es";

  const dict = await getDictionary(safeLang);
    return (
      <div>
       
                <main>
                          {children}


                </main>
      </div>
    );
  

}
